name: Automated Code Cleanup on PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md' # Ignore markdown files, adjust as needed

jobs:
  code-cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Perform Code Cleanup
      run: |
        echo "Perform code cleanup here. Insert the actual commands to clean up code."

    - name: Commit and Push Changes if Any
      run: |
        if git diff --quiet; then
          echo "No changes detected."
        else
          git checkout -b cleanup/${{ github.head_ref }}
          git add .
          git commit -m "Automated code cleanup for PR"
          git push origin cleanup/${{ github.head_ref }}
        fi

    - name: Create Pull Request for Cleanup Changes
      if: success() && !env.NO_CHANGES
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated code cleanup"
        branch: cleanup/${{ github.head_ref }}
        delete-branch: true
        title: "Automated Code Cleanup"
        body: "This PR is generated by the automated code cleanup process."
        base: ${{ github.head_ref }} # Target branch for the cleanup PR
        draft: false
